# Generated by Django 4.1.1 on 2024-02-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=150)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=558)),
            ],
        ),
    ]
