# Generated by Django 6.0.7 on 2026-08-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
